{% set name = "django-dramatiq" %}
{% set version = "0.13.0" %}
{% set python_min = "3.9" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_dramatiq-{{ version }}.tar.gz
  sha256: 1cdf723ec6a223761985c0855b92fe40cca85d364914df6d99d3034f0f6cee15

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=40.8.0
  run:
    - python >={{ python_min }}
    - django >=4.2
    - dramatiq >=1.11

test:
  imports:
    - django_dramatiq
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Bogdanp/django_dramatiq
  summary: A Django app for Dramatiq.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://github.com/Bogdanp/django_dramatiq
  dev_url: https://github.com/Bogdanp/django_dramatiq

extra:
  recipe-maintainers:
    - davner
